# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GTFS_miner
                                 A QGIS plugin
 Extraction facile des données GTFS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-08
        copyright            : (C) 2020 by Wei SI Transamo
        email                : wei.si@transamo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GTFS_miner class from file GTFS_miner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GTFS_miner import GTFS_miner
    return GTFS_miner(iface)
